// w3_Vuex/myproject/src/App.vue
<template>
  <div id="app">
    <el-row :gutter="20">
      <el-col :span="18">
        <el-menu
          :default-active="active"
          class="el-menu-demo"
          mode="horizontal"
          router
          @select="changeActive"
        >
          <el-menu-item :index="item.path" v-for="item in menu" :key="item.name">
            <!-- <router-link :to="item.path" tag="div" active-class="current"> -->
              <el-badge :value="cartlenth" class="item" v-if="item.name=='cart'">
              <i :class="item.icon"></i>
              {{item.text}}
              </el-badge>
              <template v-else>
                <i :class="item.icon"></i>
                {{item.text}}
              </template>
            <!-- </router-link> -->
          </el-menu-item>
        </el-menu>
      </el-col>
      <el-col :span="5" :offset="1">
        <el-row>
          <el-col :span="12" @click.native="goto('reg')">
            <i class="el-icon-s-custom"></i>
            注册
          </el-col>
          <el-col :span="12" @click.native="goto('login')">
            <i class="el-icon-user"></i>
            登录
          </el-col>
        </el-row>
      </el-col>
    </el-row>

    <router-view></router-view>
  </div>
</template>

<script>
import Vue from "vue";
import ElementUI from "element-ui";
Vue.use(ElementUI);

import "element-ui/lib/theme-chalk/index.css";

export default {
  name: "app",
  data() {
    return {
      active: "/home",
      menu: [
        {
          name: "home",
          text: "首页",
          path: "/home",
          icon: "el-icon-s-home"
        },
        {
          name: "cart",
          text: "购物车",
          path: "/cart",
          icon: "el-icon-shopping-cart-full"
        },
        {
          name: "discover",
          text: "发现",
          path: "/discover",
          icon: "el-icon-search"
        },
        {
          name: "mine",
          text: "我的",
          path: "/mine",
          icon: "el-icon-user-solid"
        }
      ]
    };
  },
  computed:{
    cartlenth(){
      return this.$store.state.cartlist.length;
    }
  },
  methods: {
    changeActive(index, path) {
      console.log(index, path);
      this.active = index;
    },
    goto(path){
      this.$router.push({path})
    }
  },
  created() {
    console.log(this.$route, this.$router); //this.$route获取当前路由信息
    this.active = this.$route.path;
  }
};
</script>

<style>
.current {
  color: #f00;
}
</style>

// w6_Redux/src/App.jsx
import React, { Component } from 'react';

import { Route, Redirect, Switch, withRouter } from 'react-router-dom';
import { Menu, Icon, Badge } from 'antd';
import {connect} from 'react-redux';

import Home from '~/Home';
import Mine from '~/Mine';
import Discover from '~/Discover';
import Cart from '~/Cart';
import Goods from '~/Goods';
import Login from '~/Login'
import Reg from '~/Reg'

class App extends Component {
    state = {
        current: '/home',
        menu: [{
            path: '/home',
            text: '首页',
            icon: 'home',
            name: 'home'
        }, {
            path: '/discover',
            text: '发现',
            icon: 'eye',
            name: 'discover'
        }, {
            path: '/cart',
            text: '购物车',
            icon: 'shopping-cart',
            name: 'cart'
        }, {
            path: '/mine',
            text: '我的',
            icon: 'user',
            name: 'mine'
        }]
    }


    goto = (path) => {
        // 编程式导航：通过代码实现跳转
        // 如何获取history

        this.props.history.push(path)

    }

    changeMenu = ({ key }) => {
        this.setState({
            current: key
        });
        this.goto(key)
    }

    componentDidMount() {

    }

    render() {
        let {cartlength} = this.props;
        return (
            <div>
                <Menu
                    onClick={this.changeMenu}
                    selectedKeys={[this.state.current]}
                    mode="horizontal">
                    {
                        this.state.menu.map(item => {
                            return <Menu.Item key={item.path}>
                                {
                                    item.name === 'cart' 
                                    ? 
                                    <Badge count={cartlength}>
                                        <Icon type={item.icon} />
                                        {item.text}
                                    </Badge>
                                    :
                                    <>
                                        <Icon type={item.icon} />
                                        {item.text}
                                    </>
                                }
                                

                            </Menu.Item>
                        })
                    }


                </Menu>
                <div style={{ padding: 20 }}>
                    <Switch>
                        <Route path="/home" component={Home} />
                        <Route path="/login" component={Login} />
                        <Route path="/reg" component={Reg} />
                        <Route path="/cart" component={Cart} />
                        <Route path="/mine" component={Mine} />

                        {/* 动态路由 */}
                        <Route path="/goods/:id" component={Goods} />

                        {/* 嵌套路由 */}
                        <Route path="/discover" component={Discover} />

                        <Route path="/notfound" render={() => <div>404</div>} />
                        <Redirect from="/" to="/home" exact />
                        {/* 404 一定要写在最后面*/}
                        <Redirect from="*" to="/notfound" />
                    </Switch>
                </div>
            </div>
        )
    }
}

App = withRouter(App);//返回一个新的组件 
let mapStateToProps = (state)=>{
    return {
        cartlength:state.cart.goodslist.length
    }
}
App = connect(mapStateToProps)(App);
export default App;
